### ISSUE TITLE
Why the diffuse map is blur?

### ISSUE THREAD

**Issue by YiChenCityU** [abdallahdib/NextFace#25] opened 2022-05-23 12:18 UTC
![Screen Shot 2022-05-23 at 20 12 04](https://user-images.githubusercontent.com/12424523/169817407-f56bcfcb-73b1-4afd-a717-5e92ed50d3b8.png)
Hi, I have tried many images, but the diffuse map around the eye is not fit with the 3D model and was blurry. Could you explaine it? Thanks very much.

**Comment by abdallahdib** [comment] 2022-05-27 17:49
Hi and sorry for my late response, i was busy moving to Canada, 
From the image u uploaded, it is hard to tell if the texture is misaligned with the mesh. 

Did u check how accurate are ur landmarks? in the output folder, there is an image called landmarks.png, can u upload it? please note that the optimization is sensitive to the landmarks position, in case of inaccurate landmarks u may got a misalignment of the texture and the mesh.  The bluryness is caused by the smoothness regularizer, u can try to reduce this regularizer in optimConfig.ini ( weightDiffuseSmoothnessReg). also What is the texture resolution u are using ? did u try 512 or 1024?

**Closed as completed** 2022-07-19 12:47 UTC
